# Generated by Django 5.2.3 on 2025-06-17 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_producto_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('color_barra', models.CharField(choices=[('primary', 'Azul'), ('secondary', 'Gris'), ('success', 'Verde'), ('danger', 'Rojo'), ('warning', 'Amarillo'), ('info', 'Celeste')], default='primary', max_length=20)),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
